export const textStyles = {
  hero: {
    fontFamily: 'inter',
    color: 'primary.500',
    fontWeight: 600,
    fontSize: { base: '40px', lg: '64px' },
    lineHeight: { base: '48px', lg: '72px' },
    letterSpacing: '-0.022em',
    fontFeatureSettings: "'cv05' on",
  },
  display2: {
    fontFamily: 'inter',
    color: 'primary.500',
    fontWeight: 600,
    fontSize: '40px',
    lineHeight: '48px',
    letterSpacing: '-0.022em',
    fontFeatureSettings: "'cv05' on",
  },
  h1: {
    fontFamily: 'inter',
    fontSize: '48px',
    fontWeight: 600,
    lineHeight: '60px',
    color: 'primary.500',
  },
  heading2: {
    fontFamily: 'inter',
    fontSize: '36px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '45px',
    letterSpacing: '0px',
  },
  h2: {
    fontFamily: 'inter',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '32px',
    letterSpacing: '-0.019em',
    color: 'primary.500',
  },
  h3: {
    fontFamily: 'inter',
    fontSize: '20px',
    fontWeight: 600,
    lineHeight: '32px',
    letterSpacing: '-0.014em',
    color: 'primary.500',
  },
  sub1: {
    fontFamily: 'inter',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '-0.011em',
    color: 'neutral.800',
  },
  sub2: {
    fontFamily: 'inter',
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: '24px',
    letterSpacing: '-0.006em',
    color: 'neutral.900',
  },
  sub3: {
    fontFamily: 'inter',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'neutral.700',
  },
  body1: {
    fontFamily: 'inter',
    fontWeight: 'normal',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '-0.011em',
    color: 'neutral.800',
  },
  body2: {
    fontFamily: 'inter',
    fontWeight: 'normal',
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: '-0.006em',
    color: '#696969',
  },
  button2: {
    fontSize: '14px',
    fontWeight: 600,
    lineHeight: '21px',
    letterSpacing: '0.5px',
    fontFamily: 'ssp',
  },
}
