export const textStyles = {
  display1: {
    fontSize: '4rem',
    lineHeight: '4.5rem',
    fontWeight: 700,
    letterSpacing: '-0.022em',
  },
  display2: {
    fontSize: '2.5rem',
    lineHeight: '3rem',
    fontWeight: 500,
    letterSpacing: '-0.022em',
    fontFeatureSettings: "'cv05' on",
  },
  heading1: {
    fontSize: '3.375rem',
    lineHeight: '4rem',
    fontWeight: 300,
    letterSpacing: '-0.022em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  heading2: {
    fontSize: '1.75rem',
    lineHeight: '2rem',
    fontWeight: 500,
    letterSpacing: '-0.019em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  heading3: {
    fontSize: '1.125rem',
    lineHeight: '1.5rem',
    fontWeight: 500,
    letterSpacing: '-0.014em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  subtitle1: {
    fontSize: '1rem',
    lineHeight: '1.5rem',
    fontWeight: 600,
    letterSpacing: '-0.011em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  subtitle2: {
    fontSize: '0.875rem',
    lineHeight: '1.5rem',
    fontWeight: 500,
    letterSpacing: '-0.006em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  subtitle3: {
    fontSize: '0.875rem',
    lineHeight: '1.5rem',
    fontWeight: 600,
    letterSpacing: '-0.08em',
    textTransform: 'uppercase',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  body1: {
    fontSize: '1rem',
    lineHeight: '1.5rem',
    fontWeight: 400,
    letterSpacing: '-0.011em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  body2: {
    fontSize: '0.875rem',
    lineHeight: '1.5rem',
    fontWeight: 400,
    letterSpacing: '-0.006em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  caption1: {
    fontSize: '0.75rem',
    lineHeight: '1rem',
    fontWeight: 400,
    letterSpacing: '0em',
    fontFeatureSettings: "'tnum' on, 'lnum' on, 'cv05' on",
  },
  hero: {
    fontFamily: 'inter',
    color: 'primary.500',
    fontWeight: 600,
    fontSize: { base: '40px', lg: '64px' },
    lineHeight: { base: '48px', lg: '72px' },
    letterSpacing: '-0.022em',
    fontFeatureSettings: "'cv05' on",
  },
  h1: {
    fontFamily: 'inter',
    fontSize: '48px',
    fontWeight: 600,
    lineHeight: '60px',
    color: 'primary.500',
  },
  // Legacy - To remove
  h2: {
    fontFamily: 'inter',
    fontSize: '24px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '32px',
    letterSpacing: '-0.019em',
    color: 'primary.500',
  },
  h3: {
    fontFamily: 'inter',
    fontSize: '20px',
    fontWeight: 600,
    lineHeight: '32px',
    letterSpacing: '-0.014em',
    color: 'primary.500',
  },
  sub1: {
    fontFamily: 'inter',
    fontWeight: 500,
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '-0.011em',
    color: 'neutral.800',
  },
  sub2: {
    fontFamily: 'inter',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '24px',
    letterSpacing: '-0.006em',
    color: 'neutral.900',
  },
  sub3: {
    fontFamily: 'inter',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'neutral.700',
  },
  button2: {
    fontSize: '14px',
    fontWeight: 600,
    lineHeight: '21px',
    letterSpacing: '0.5px',
    fontFamily: 'ssp',
  },
}
